export const graphData = {
  weeklySales: [
    { name: "Jan", value: 10 },
    { name: "Feb", value: 20 },
    { name: "Mar", value: 15 },
    { name: "Apr", value: 25 },
    { name: "May", value: 30 },
    { name: "Jun", value: 28 },
    { name: "Jul", value: 35 },
    { name: "Aug", value: 40 },
    { name: "Sep", value: 38 },
    { name: "Oct", value: 45 },
    { name: "Nov", value: 50 },
    { name: "Dec", value: 42 },
  ],

  newUsers: [
    { name: "Jan", value: 5 },
    { name: "Feb", value: 12 },
    { name: "Mar", value: 10 },
    { name: "Apr", value: 18 },
    { name: "May", value: 22 },
    { name: "Jun", value: 26 },
    { name: "Jul", value: 28 },
    { name: "Aug", value: 30 },
    { name: "Sep", value: 32 },
    { name: "Oct", value: 35 },
    { name: "Nov", value: 38 },
    { name: "Dec", value: 40 },
  ],

  purchaseOrders: [
    { name: "Jan", value: 8 },
    { name: "Feb", value: 12 },
    { name: "Mar", value: 10 },
    { name: "Apr", value: 18 },
    { name: "May", value: 20 },
    { name: "Jun", value: 24 },
    { name: "Jul", value: 26 },
    { name: "Aug", value: 30 },
    { name: "Sep", value: 28 },
    { name: "Oct", value: 32 },
    { name: "Nov", value: 35 },
    { name: "Dec", value: 38 },
  ],

  messages: [
    { name: "Jan", value: 6 },
    { name: "Feb", value: 10 },
    { name: "Mar", value: 8 },
    { name: "Apr", value: 14 },
    { name: "May", value: 18 },
    { name: "Jun", value: 22 },
    { name: "Jul", value: 24 },
    { name: "Aug", value: 28 },
    { name: "Sep", value: 26 },
    { name: "Oct", value: 30 },
    { name: "Nov", value: 34 },
    { name: "Dec", value: 36 },
  ],
};